import React, { useState } from 'react'
const Home = () => {

    const currencies=[
        "$myro",
            "$wen",
            "00",
            "1000sats",
            "1inch",
            "aave",
            "abt",
            "ach",
            "acs",
            "ada",
            "aed",
            "aergo",
            "aero",
            "afn",
            "agix",
            "agld",
            "aioz",
            "ai",
            "akt",
            "alcx",
            "aleph",
            "alex",
            "algo",
            "alice", 
            "all", 
            "alph",
            "alt", 
            "alusd", 
            "amd", 
            "amp", 
            "ang", 
            "ankr", 
            "ant",
            "aoa", 
            "ape",
            "apex",
            "api3", 
            "apt", 
            "ar", 
            "arb", 
            "ark", 
            "arkm", 
            "arpa", 
            "ars",
            "asm", 
            "ast",
            "astr", 
            "ata",
            "atom", 
            "ats", 
            "auction", 
            "aud",
            "audio",
            "aurora",
            "avax",
            "avt",
            "awg",
            "axl",
            "axs",
            "azero",
            "azm",
            "azn",
            "babydoge",
            "badger",
            "bake",
            "bal", 
            "bam",
            "band", 
            "bat",
            "bbd",
            "bch",
            "bdt", 
            "bdx", 
            "beam", 
            "bef", 
            "bgb",
            "bgn",
            "bhd",
            "bico",
            "bif", 
            "bigtime",
            "bit",
            "bld",
            "blur",
            "blz",
            "bmd",
            "bnb", 
            "bnd",
            "bnt",
            "bob", 
            "boba", 
            "bond",
            "bonk", 
            "bora",
            "borg", 
            "brl",
            "bsd", 
            "bsv", 
            "bsw", 
            "btc", 
            "btc.b",
            "btcb",
            "btg", 
            "btn",
            "btrst", 
            "btt",
            "busd", 
            "bwp", 
            "byn", 
            "byr", 
            "bzd", 
            "c98", 
            "cad",
            "cake", 
            "canto", 
            "cbeth",
            "cdai",
            "cdf",
            "cdt", 
            "celo", 
            "celr", 
            "ceth", 
            "cfg",
            "cfx", 
            "cgld", 
            "cheel", 
            "chf", 
            "chr", 
            "chz",
            "ckb",
            "clp", 
            "clv", 
            "cnh",
            "cny", 
            "comai", 
            "comp", 
            "cop", 
            "corgiai", 
            "coti", 
            "coval", 
            "cqt", 
            "crc", 
            "cro", 
            "crpt", 
            "crv",
            "cspr", 
            "ctc",
            "ctsi",
            "ctx",
            "cuc",
            "cup",
            "cvc", 
            "cve",
            "cvx",
            "cwbtc", 
            "cyp",
            "czk", 
            "dag", 
            "dai", 
            "dao",
            "dar",
            "dash",
            "dcr", 
            "ddx",
            "dem", 
            "deso", 
      
              "dexe",
              "dext",
              "dfi",
              "dia",
              "dimo",
              "djf",
              "dkk",
              "dnt",
              "doge",
              "dop",
              "dora",
              "dot",
              "drep",
              "dydx",
              "dym",
              "dyp",
              "dzd",
              "edu",
              "edum",
              "eek",
              "egld",
              "egp",
              "ela",
              "elf",
              "elg",
              "enj",
              "ens",
              "eos",
              "ern",
              "esp",
              "etb",
              "etc",
              "eth",
              "eth2",
              "ethdydx",
              "ethw",
              "ethx",
              "eur",
              "euroc",
              "ever",
              "farm",
              "fdusd",
              "fei",
              "fet",
              "fida",
              "fil",
              "fim",
                "fis",
                "fjd",
                "fkp",
                "floki",
                "flow",
                "flr",
                "flux",
                "fnsa",
                "fort",
                "forth",
                "fox",
                "frax",
                "frf",
                "frxeth",
                "ftm",
                "ftn",
                "ftt",
                "fx",
                "fxs",
                "gaj",
                "gal",
                "gala",
                "gas",
                "gbp",
                "gel",
                "gfi",
                "ggp",
                "ghc",
                "ghs",
                "ghst",
                "gip",
                "glm",
                "glmr",
                "gmd",
                "gmt",
                "gmx",
                "gnf",
                "gno",
                "gns",
                "gnt",
                "gods",
                "grd",
                "grt",
                "gst",
                "gt",
                "gtc",
                "gtq",
                "gusd",
                "gxc",
                "gyd",
                "gyen",
                "hbar",
                "hbtc",
                "hft",
                "high",
                "hkd",
                "hnl",
                "hnt",
                "honey",
                "hopr",
                "hot",
                "hrk",
                "ht",
                "htg",
                "huf",
                "icp",
                "icx",
                "id",
                "idex",
                "idr",
                "iep",
                "ils",
                "ilv",
                "imp",
                "imx",
                "index",
                "inj",
                "inr",
                "inv",
                "iost",
                "iota",
                "iotx",
                "iqd",
                "irr",
                "isk",
                "itl",
                "jasmy",
                "jep",
                "jmd",
                "jod",
                "joe",
                "jpy",
                "jst",
                "jto",
                "jup",
                "kas",
                "kava",
                "kcs",
                "kda",
                "keep",
                "kes",
                "kgs",
                "khr",
                "klay",
                "kmf",
                "knc",
                "kpw",
                "krl",
                "krw",
                "ksm",
                "kub",
                "kuji",
                "kwd",
                "kyd",
                "kzt",
                "lak",
                "lbp",
                "lcx",
                "ldo",
                "leo",
                "link",
                "lit",
                "lkr",
                "loka",
                "loom",
                "lpt",
                "lqty",
                "lrc",
                "lrd",
                "lseth",
                "lsk",
                "lsl",
                "ltc",
                "ltl",
                "luf",
                "luna",
                "lunc",
                "lusd",
                "lvl",
                "lyd",
                "lyx",
                "lyxe",
                "mad",
                "magic",
                "mana",
                "manta",
                "mask",
                  "math", "matic", "mav", "mavia", "mbx", "mco2", "mdl", "mdt", "media", "meme", 
                  "meth", "metis", "mga", "mgf", "mina", "mir", "mkd", "mkr", "mkusd", "mln", 
                  "mmk", "mnde", "mnt", "mobile", "mona", "mop", "movr", "mpl", "mro", "mru", 
                  "msol", "mtl", "mubi", "multi", "mur", "muse", "mvr", "mwk", "mx", "mxc", 
                  "mxn", "mxv", "myr", "mzm", "mzn", "nad", "nct", "near", "neo", "neon", "nest", 
                  "nexo", "nft", "ngn", "nio", "nkn", "nlg", "nmr", "nok", "nos", "npr", "ntrn", 
                  "nu", "nxm", "nzd", "oas", "ocean", "ogn", "ohm", "okb", "okt", "olas", "om", 
                  "omg", "omi", "omr", "ondo", "one", "ont", "ooki", "op", "orca", "ordi", "orn", 
                  "osmo", "ox", "oxt", "paal", "pab", "pandora", "pax", "paxg", "pen", "pendle", 
                  "people", "pepe", "perp", "pgk", "php", "pixel", "pkr", "pla", "pln", "plu", 
                  "png", "pokt", "pols", "poly", "polyx", "pond", "pork", "powr", "prime", "pro", 
                  "prom", "prq", "pte", "pundix", "pyg", "pyr", "pyth", "pyusd", "qar", "qi", 
                  "qnt", "qsp", "qtum", "quick", "rad", "rai", "rare", "rari", "ray", "rbn", 
                  "ren", "render", "rep", "repv2", "req", "reth", "rgt", "rif", "rlb", "rlc", 
                  "rly", "rndr", "rol", "ron", "rose", "rpl", "rsd", "rub", "rune", "rvn", "rwf", 
                  "sand", "sar", "sats", "savax", "sbd", "sc", "scr", "sdd", "sdg", "seam", "sei", 
                  "sek", "sfp", "sfrxeth", "sfund", "sgb", "sgd", "shdw", "shib", "shp", "shping", 
                  "sit", "skk", "skl", "sle", "sll", "snt",
                
                    "snx",
                    "sol",
                    "sos",
                    "spa",
                    "spell",
                    "spl",
                    "srd",
                    "srg",
                    "ssp",
                    "ssv",
                    "std",
                    "steth",
                    "stg",
                    "stn",
                    "storj",
                    "strax",
                    "strd",
                    "strk",
                    "stsol",
                    "stx",
                    "sui",
                    "suku",
                    "super",
                    "sushi",
                    "svc",
                    "sweth",
                    "swftc",
                    "sxp",
                    "sylo",
                    "syn",
                    "syp",
                    "szl",
                    "t",
                    "tao",
                    "tet",
                    "tfuel",
                    "thb",
                    "theta",
                    "tia",
                    "time",
                    "tjs",
                    "tkx",
                    "tmm",
                    "tmt",
                    "tnd",
                    "ton",
                    "tone",
                    "top",
                    "topia",
                    "trac",
                    "trb",
                    "tribe",
                    "trl",
                    "tru",
                    "trx",
                    "try",
                    "ttd",
                    "ttt",
                    "tusd",
                    "tvd",
                    "tvk",
                    "twd",
                    "twt",
                    "tzs",
                    "uah",
                    "ugx",
                    "uma",
                    "unfi",
                    "uni",
                    "upi",
                    "uqc",
                    "usd",
                    "usdc",
                    "usdd",
                    "usde",
                    "usdp",
                    "usdt",
                    "ust",
                    "ustc",
                    "uyu",
                    "uzs",
                    "val",
                    "vara",
                    "veb",
                    "ved",
                    "vef",
                    "velo",
                    "ves",
                    "vet",
                    "vgx",
                    "vnd",
                    "vnst",
                    "voxel",
                    "vr",
                    "vtho",
                    "vuv",
                    "wampl",
                    "waves",
                    "waxl",
                    "waxp",
                    "wbeth",
                    "wbt",
                    "wbtc",
                    "wcfg",
                    "wemix",
                    "whrh",
                    "wif",
                    "wld",
                    "wluna",
                    "woo",
                    "wst",
                    "xaf",
                    "xag",
                    "xai",
                    "xau",
                    "xaut",
                    "xbt",
                    "xcd",
                    "xch",
                    "xcn",
                    "xdc",
                    "xdr",
                    "xec",
                    "xem",
                    "xlm",
                    "xmon",
                    "xmr",
                    "xof",
                    "xpd",
                    "xpf",
                    "xpt",
                    "xrd",
                    "xrp",
                    "xtz",
                    "xvs",
                    "xyo",
                    "yer",
                    "yfi",
                    "yfii",
                    "zar",
                    "zec",
                    "zen",
                    "zeta",
                    "zil",
                    "zmk",
                    "zmw",
                    "zrx",
                    "zwd",
                    "zwl",
                  
                  
      ]

      const [from,setForm]=useState("$myro")
      const [to,setTo]=useState("$myro")
      const [amount,setAmount]=useState(1)
      const [isSubmmited,setIsSubmitted]=useState(false)
      const [convertedValue,setConvertedValue]=useState(1)

      async function handleConverison(e){
        e.preventDefault()
        const data= await fetch(`https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/${from}.json`)
        const curr = await data.json();
        const conversionRate=curr[from][to]
        setIsSubmitted(true)
        console.log(conversionRate)
        setConvertedValue(amount*conversionRate)
      }

      
    
  return (
    <div >
  <h1 className="text-7xl pt-10 font-bold text-center">
      Currency Converter
    </h1>

    <div className='pt-20 text-3xl flex place-content-center'>

      <form className='bg-gray-100 text-left ' onSubmit={handleConverison}>
        <div className='flex md:flex-row flex-col'>

        
        <div className='px-10 py-5'>
        <label className='text-green-500  font-bold'>Amount</label>
        <br/>
        <br/>
        <input type='number' value={amount} onChange={(e)=>{setAmount(e.target.value)}} ></input>
        
        </div>
        
        <div className='px-10 py-5'>
        <label className='text-green-500 font-bold'>From</label>
        <br/>
        <br/>
        <select id="from" name="from" value={from} onChange={(e)=>{setForm(e.target.value)}} >
        {currencies.map((currency,index)=>(
                <option key={index} value={`${currency}`}>{currency}</option>

        ))}
        </select>

        </div>
        
        <div className='px-10 py-5'>
        <label className='text-green-500 font-bold py-2'>To </label>
        <br/>
        <br/>
        <select  id="to" name="to" value={to} onChange={(e)=>{setTo(e.target.value)}}>
        {currencies.map((currency,index)=>(
                <option key={index} value={`${currency}`}>{currency}</option>
        ))}
        </select>
        </div>
        </div>
        <div className='px-10'>
        <input className=' bg-green-200  text-green-600 hover:text-green-400 border-2 border-green-600 w-32 h-10 font-bold ' type='submit' value="Convert"/>

        </div>
         {isSubmmited &&
    (
      <div className='pt-10'>
      <div className='pt-3 text-3xl text-left flex  py-5'>
          <h2 className='font-bold px-10'>
            Converted Amount:
          </h2>

        </div>
        <div>
         <h2 className='text-green-500 px-10'>{amount}{" "}{from} = {convertedValue}{" "}{to}</h2>

        </div>
        </div>
    )}
      
      </form>
    </div>
   
    </div>
  )
}

export default Home
